/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_saorsa_android_jni_java_JniSamples */

#ifndef _Included_com_saorsa_android_jni_java_JniSamples
#define _Included_com_saorsa_android_jni_java_JniSamples
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_saorsa_android_jni_java_JniSamples
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_saorsa_android_jni_java_JniSamples_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_saorsa_android_jni_java_JniSamples
 * Method:    concatenate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_saorsa_android_jni_java_JniSamples_concatenate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_saorsa_android_jni_java_JniSamples
 * Method:    getHello
 * Signature: (Lcom/saorsa/android/jni/java/JavaObject;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_saorsa_android_jni_java_JniSamples_getHello
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_saorsa_android_jni_java_JniSamples
 * Method:    useJavaObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_saorsa_android_jni_java_JniSamples_useJavaObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
